version: '3.8'
services:
  mongo:
    image: mongo:4.4
    container_name: gym-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: gym-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/gymtracker
      - JWT_SECRET=your_jwt_secret_here
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: gym-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: 